# Generated by Django 4.1.7 on 2023-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifa',
            name='sifati',
            field=models.CharField(choices=[('namunali', 'namunali'), ('yaxshi', 'yaxshi'), ('qoniqasiz', 'qoniqasiz')], max_length=50),
        ),
    ]
