# Generated by Django 4.1.7 on 2023-02-19 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_list', '0002_alter_vazifa_sifati'),
    ]

    operations = [
        migrations.AddField(
            model_name='vazifa',
            name='qushilgansana',
            field=models.DateField(default=datetime.datetime(2023, 2, 19, 17, 44, 16, 385587), null=True),
        ),
    ]
