# Generated by Django 4.1.7 on 2023-02-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_list', '0003_vazifa_qushilgansana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifa',
            name='qushilgansana',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 22, 9, 7, 232313), null=True),
        ),
    ]
