# Generated by Django 4.1.7 on 2023-02-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazifa_list', '0004_alter_vazifa_qushilgansana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifa',
            name='qushilgansana',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 17, 15, 50, 344034), null=True),
        ),
    ]
