# Generated by Django 4.1.7 on 2023-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAdmissionWhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('page', models.CharField(choices=[('About', 'About'), ('Admission', 'Admission'), ('WhyUs', 'WhyUs')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='WhyUs',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
